// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cgetPaths
arma::mat cgetPaths(std::string filepath);
RcppExport SEXP _LIEB_cgetPaths(SEXP filepathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filepath(filepathSEXP);
    rcpp_result_gen = Rcpp::wrap(cgetPaths(filepath));
    return rcpp_result_gen;
END_RCPP
}
// crowMatch
arma::uvec crowMatch(arma::mat assoc, arma::mat nonconsec);
RcppExport SEXP _LIEB_crowMatch(SEXP assocSEXP, SEXP nonconsecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type assoc(assocSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type nonconsec(nonconsecSEXP);
    rcpp_result_gen = Rcpp::wrap(crowMatch(assoc, nonconsec));
    return rcpp_result_gen;
END_RCPP
}
// get_list_names
std::vector<std::string> get_list_names(Rcpp::List L);
RcppExport SEXP _LIEB_get_list_names(SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(get_list_names(L));
    return rcpp_result_gen;
END_RCPP
}
// cpaste0
std::string cpaste0(std::vector<std::string> str1);
RcppExport SEXP _LIEB_cpaste0(SEXP str1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type str1(str1SEXP);
    rcpp_result_gen = Rcpp::wrap(cpaste0(str1));
    return rcpp_result_gen;
END_RCPP
}
// cstr_split
arma::mat cstr_split(std::vector<std::string> strings, std::string split);
RcppExport SEXP _LIEB_cstr_split(SEXP stringsSEXP, SEXP splitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type strings(stringsSEXP);
    Rcpp::traits::input_parameter< std::string >::type split(splitSEXP);
    rcpp_result_gen = Rcpp::wrap(cstr_split(strings, split));
    return rcpp_result_gen;
END_RCPP
}
// trans_func
int trans_func(double& x);
RcppExport SEXP _LIEB_trans_func(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(trans_func(x));
    return rcpp_result_gen;
END_RCPP
}
// caccept
arma::vec caccept(arma::mat x, arma::colvec y);
RcppExport SEXP _LIEB_caccept(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(caccept(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cget_prior_count
arma::colvec cget_prior_count(arma::mat red_class, Rcpp::List mus, arma::mat labels, int d, int n, int dist_tol);
RcppExport SEXP _LIEB_cget_prior_count(SEXP red_classSEXP, SEXP musSEXP, SEXP labelsSEXP, SEXP dSEXP, SEXP nSEXP, SEXP dist_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type red_class(red_classSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type mus(musSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type dist_tol(dist_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cget_prior_count(red_class, mus, labels, d, n, dist_tol));
    return rcpp_result_gen;
END_RCPP
}
// creduce_by_hamming
arma::colvec creduce_by_hamming(arma::mat red_class, arma::colvec fullidx, int hamming_tol, int M);
RcppExport SEXP _LIEB_creduce_by_hamming(SEXP red_classSEXP, SEXP fullidxSEXP, SEXP hamming_tolSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type red_class(red_classSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type fullidx(fullidxSEXP);
    Rcpp::traits::input_parameter< int >::type hamming_tol(hamming_tolSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(creduce_by_hamming(red_class, fullidx, hamming_tol, M));
    return rcpp_result_gen;
END_RCPP
}
// cget_true_assoc_idx
arma::colvec cget_true_assoc_idx(arma::mat red_class, arma::mat true_assoc);
RcppExport SEXP _LIEB_cget_true_assoc_idx(SEXP red_classSEXP, SEXP true_assocSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type red_class(red_classSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type true_assoc(true_assocSEXP);
    rcpp_result_gen = Rcpp::wrap(cget_true_assoc_idx(red_class, true_assoc));
    return rcpp_result_gen;
END_RCPP
}
// cassociate
arma::mat cassociate(arma::mat& paths, std::string filepath, int len_filt_h);
RcppExport SEXP _LIEB_cassociate(SEXP pathsSEXP, SEXP filepathSEXP, SEXP len_filt_hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type paths(pathsSEXP);
    Rcpp::traits::input_parameter< std::string >::type filepath(filepathSEXP);
    Rcpp::traits::input_parameter< int >::type len_filt_h(len_filt_hSEXP);
    rcpp_result_gen = Rcpp::wrap(cassociate(paths, filepath, len_filt_h));
    return rcpp_result_gen;
END_RCPP
}
// abs3
double abs3(double val);
RcppExport SEXP _LIEB_abs3(SEXP valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type val(valSEXP);
    rcpp_result_gen = Rcpp::wrap(abs3(val));
    return rcpp_result_gen;
END_RCPP
}
// SCAD_1d
arma::rowvec SCAD_1d(arma::rowvec prop, double lambda, int k, double a);
RcppExport SEXP _LIEB_SCAD_1d(SEXP propSEXP, SEXP lambdaSEXP, SEXP kSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type prop(propSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(SCAD_1d(prop, lambda, k, a));
    return rcpp_result_gen;
END_RCPP
}
// double_SCAD_1d
double double_SCAD_1d(double prop, double lambda, double a);
RcppExport SEXP _LIEB_double_SCAD_1d(SEXP propSEXP, SEXP lambdaSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prop(propSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(double_SCAD_1d(prop, lambda, a));
    return rcpp_result_gen;
END_RCPP
}
// SCAD
arma::rowvec SCAD(arma::rowvec prop, double lambda, int k, double a);
RcppExport SEXP _LIEB_SCAD(SEXP propSEXP, SEXP lambdaSEXP, SEXP kSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type prop(propSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(SCAD(prop, lambda, k, a));
    return rcpp_result_gen;
END_RCPP
}
// double_SCAD
double double_SCAD(double prop, double lambda, double a);
RcppExport SEXP _LIEB_double_SCAD(SEXP propSEXP, SEXP lambdaSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type prop(propSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(double_SCAD(prop, lambda, a));
    return rcpp_result_gen;
END_RCPP
}
// Mahalanobis
arma::vec Mahalanobis(arma::mat x, arma::rowvec mu, arma::mat sigma);
RcppExport SEXP _LIEB_Mahalanobis(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(Mahalanobis(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cdmvnorm
arma::vec cdmvnorm(arma::mat x, arma::rowvec mu, arma::mat sigma);
RcppExport SEXP _LIEB_cdmvnorm(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cdmvnorm(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cget_constr_sigma
arma::mat cget_constr_sigma(arma::rowvec sigma, double rho, arma::rowvec combos, int d);
RcppExport SEXP _LIEB_cget_constr_sigma(SEXP sigmaSEXP, SEXP rhoSEXP, SEXP combosSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type combos(combosSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cget_constr_sigma(sigma, rho, combos, d));
    return rcpp_result_gen;
END_RCPP
}
// func_to_optim
double func_to_optim(const arma::colvec& init_val, arma::mat& x, arma::mat& h_est, arma::mat& combos);
RcppExport SEXP _LIEB_func_to_optim(SEXP init_valSEXP, SEXP xSEXP, SEXP h_estSEXP, SEXP combosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type init_val(init_valSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type h_est(h_estSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type combos(combosSEXP);
    rcpp_result_gen = Rcpp::wrap(func_to_optim(init_val, x, h_est, combos));
    return rcpp_result_gen;
END_RCPP
}
// optim_rcpp
arma::vec optim_rcpp(const arma::vec& init_val, arma::mat& x, arma::mat& h_est, arma::mat& combos);
RcppExport SEXP _LIEB_optim_rcpp(SEXP init_valSEXP, SEXP xSEXP, SEXP h_estSEXP, SEXP combosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type init_val(init_valSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type h_est(h_estSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type combos(combosSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_rcpp(init_val, x, h_est, combos));
    return rcpp_result_gen;
END_RCPP
}
// func_to_optim_bound
double func_to_optim_bound(const arma::colvec& init_val, arma::mat& x, arma::mat& h_est, arma::mat& combos, double& bound);
RcppExport SEXP _LIEB_func_to_optim_bound(SEXP init_valSEXP, SEXP xSEXP, SEXP h_estSEXP, SEXP combosSEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type init_val(init_valSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type h_est(h_estSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type combos(combosSEXP);
    Rcpp::traits::input_parameter< double& >::type bound(boundSEXP);
    rcpp_result_gen = Rcpp::wrap(func_to_optim_bound(init_val, x, h_est, combos, bound));
    return rcpp_result_gen;
END_RCPP
}
// optim_rcpp_bound
arma::vec optim_rcpp_bound(const arma::vec& init_val, arma::mat& x, arma::mat& h_est, arma::mat& combos, double& bound);
RcppExport SEXP _LIEB_optim_rcpp_bound(SEXP init_valSEXP, SEXP xSEXP, SEXP h_estSEXP, SEXP combosSEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type init_val(init_valSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type h_est(h_estSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type combos(combosSEXP);
    Rcpp::traits::input_parameter< double& >::type bound(boundSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_rcpp_bound(init_val, x, h_est, combos, bound));
    return rcpp_result_gen;
END_RCPP
}
// cfconstr_pgmm
Rcpp::List cfconstr_pgmm(arma::mat& x, arma::rowvec prop, arma::mat mu, arma::mat sigma, double rho, arma::mat combos, int k, arma::rowvec df, int lambda, int citermax, double tol, unsigned int LASSO, double bound);
RcppExport SEXP _LIEB_cfconstr_pgmm(SEXP xSEXP, SEXP propSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP rhoSEXP, SEXP combosSEXP, SEXP kSEXP, SEXP dfSEXP, SEXP lambdaSEXP, SEXP citermaxSEXP, SEXP tolSEXP, SEXP LASSOSEXP, SEXP boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type prop(propSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type combos(combosSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type citermax(citermaxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type LASSO(LASSOSEXP);
    Rcpp::traits::input_parameter< double >::type bound(boundSEXP);
    rcpp_result_gen = Rcpp::wrap(cfconstr_pgmm(x, prop, mu, sigma, rho, combos, k, df, lambda, citermax, tol, LASSO, bound));
    return rcpp_result_gen;
END_RCPP
}
// cduvnorm
arma::colvec cduvnorm(arma::colvec x, double mu, double sigma);
RcppExport SEXP _LIEB_cduvnorm(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cduvnorm(x, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cmarg_ll_gmm
double cmarg_ll_gmm(arma::mat& z, arma::mat mu, arma::mat sigma, arma::rowvec prop, arma::mat combos, int k);
RcppExport SEXP _LIEB_cmarg_ll_gmm(SEXP zSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP propSEXP, SEXP combosSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type prop(propSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type combos(combosSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cmarg_ll_gmm(z, mu, sigma, prop, combos, k));
    return rcpp_result_gen;
END_RCPP
}
// cll_gmm
double cll_gmm(arma::mat& z, arma::mat mu, arma::mat sigma, double rho, arma::rowvec prop, arma::mat combos, int k);
RcppExport SEXP _LIEB_cll_gmm(SEXP zSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP rhoSEXP, SEXP propSEXP, SEXP combosSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type prop(propSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type combos(combosSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(cll_gmm(z, mu, sigma, rho, prop, combos, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LIEB_cgetPaths", (DL_FUNC) &_LIEB_cgetPaths, 1},
    {"_LIEB_crowMatch", (DL_FUNC) &_LIEB_crowMatch, 2},
    {"_LIEB_get_list_names", (DL_FUNC) &_LIEB_get_list_names, 1},
    {"_LIEB_cpaste0", (DL_FUNC) &_LIEB_cpaste0, 1},
    {"_LIEB_cstr_split", (DL_FUNC) &_LIEB_cstr_split, 2},
    {"_LIEB_trans_func", (DL_FUNC) &_LIEB_trans_func, 1},
    {"_LIEB_caccept", (DL_FUNC) &_LIEB_caccept, 2},
    {"_LIEB_cget_prior_count", (DL_FUNC) &_LIEB_cget_prior_count, 6},
    {"_LIEB_creduce_by_hamming", (DL_FUNC) &_LIEB_creduce_by_hamming, 4},
    {"_LIEB_cget_true_assoc_idx", (DL_FUNC) &_LIEB_cget_true_assoc_idx, 2},
    {"_LIEB_cassociate", (DL_FUNC) &_LIEB_cassociate, 3},
    {"_LIEB_abs3", (DL_FUNC) &_LIEB_abs3, 1},
    {"_LIEB_SCAD_1d", (DL_FUNC) &_LIEB_SCAD_1d, 4},
    {"_LIEB_double_SCAD_1d", (DL_FUNC) &_LIEB_double_SCAD_1d, 3},
    {"_LIEB_SCAD", (DL_FUNC) &_LIEB_SCAD, 4},
    {"_LIEB_double_SCAD", (DL_FUNC) &_LIEB_double_SCAD, 3},
    {"_LIEB_Mahalanobis", (DL_FUNC) &_LIEB_Mahalanobis, 3},
    {"_LIEB_cdmvnorm", (DL_FUNC) &_LIEB_cdmvnorm, 3},
    {"_LIEB_cget_constr_sigma", (DL_FUNC) &_LIEB_cget_constr_sigma, 4},
    {"_LIEB_func_to_optim", (DL_FUNC) &_LIEB_func_to_optim, 4},
    {"_LIEB_optim_rcpp", (DL_FUNC) &_LIEB_optim_rcpp, 4},
    {"_LIEB_func_to_optim_bound", (DL_FUNC) &_LIEB_func_to_optim_bound, 5},
    {"_LIEB_optim_rcpp_bound", (DL_FUNC) &_LIEB_optim_rcpp_bound, 5},
    {"_LIEB_cfconstr_pgmm", (DL_FUNC) &_LIEB_cfconstr_pgmm, 13},
    {"_LIEB_cduvnorm", (DL_FUNC) &_LIEB_cduvnorm, 3},
    {"_LIEB_cmarg_ll_gmm", (DL_FUNC) &_LIEB_cmarg_ll_gmm, 6},
    {"_LIEB_cll_gmm", (DL_FUNC) &_LIEB_cll_gmm, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_LIEB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
