# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cgetPaths <- function(filepath) {
    .Call(`_CLIMB_cgetPaths`, filepath)
}

crowMatch <- function(assoc, nonconsec) {
    .Call(`_CLIMB_crowMatch`, assoc, nonconsec)
}

get_list_names <- function(L) {
    .Call(`_CLIMB_get_list_names`, L)
}

cpaste0 <- function(str1) {
    .Call(`_CLIMB_cpaste0`, str1)
}

cstr_split <- function(strings, split) {
    .Call(`_CLIMB_cstr_split`, strings, split)
}

trans_func <- function(x) {
    .Call(`_CLIMB_trans_func`, x)
}

caccept <- function(x, y) {
    .Call(`_CLIMB_caccept`, x, y)
}

cget_prior_count <- function(red_class, mus, labels, d, n, dist_tol = 0L) {
    .Call(`_CLIMB_cget_prior_count`, red_class, mus, labels, d, n, dist_tol)
}

creduce_by_hamming <- function(red_class, fullidx, hamming_tol, M) {
    .Call(`_CLIMB_creduce_by_hamming`, red_class, fullidx, hamming_tol, M)
}

cget_true_assoc_idx <- function(red_class, true_assoc) {
    .Call(`_CLIMB_cget_true_assoc_idx`, red_class, true_assoc)
}

cassociate <- function(paths, filepath, len_filt_h) {
    .Call(`_CLIMB_cassociate`, paths, filepath, len_filt_h)
}

abs3 <- function(val) {
    .Call(`_CLIMB_abs3`, val)
}

SCAD_1d <- function(prop, lambda, k, a = 3.7) {
    .Call(`_CLIMB_SCAD_1d`, prop, lambda, k, a)
}

double_SCAD_1d <- function(prop, lambda, a = 3.7) {
    .Call(`_CLIMB_double_SCAD_1d`, prop, lambda, a)
}

SCAD <- function(prop, lambda, k, a = 3.7) {
    .Call(`_CLIMB_SCAD`, prop, lambda, k, a)
}

double_SCAD <- function(prop, lambda, a = 3.7) {
    .Call(`_CLIMB_double_SCAD`, prop, lambda, a)
}

Mahalanobis <- function(x, mu, sigma) {
    .Call(`_CLIMB_Mahalanobis`, x, mu, sigma)
}

cdmvnorm <- function(x, mu, sigma) {
    .Call(`_CLIMB_cdmvnorm`, x, mu, sigma)
}

cget_constr_sigma <- function(sigma, rho, combos, d) {
    .Call(`_CLIMB_cget_constr_sigma`, sigma, rho, combos, d)
}

func_to_optim <- function(init_val, x, h_est, combos) {
    .Call(`_CLIMB_func_to_optim`, init_val, x, h_est, combos)
}

optim_rcpp <- function(init_val, x, h_est, combos) {
    .Call(`_CLIMB_optim_rcpp`, init_val, x, h_est, combos)
}

func_to_optim_bound <- function(init_val, x, h_est, combos, bound) {
    .Call(`_CLIMB_func_to_optim_bound`, init_val, x, h_est, combos, bound)
}

optim_rcpp_bound <- function(init_val, x, h_est, combos, bound) {
    .Call(`_CLIMB_optim_rcpp_bound`, init_val, x, h_est, combos, bound)
}

cfconstr_pgmm <- function(x, prop, mu, sigma, rho, combos, k, df, lambda, citermax, tol, LASSO, bound = 0.0) {
    .Call(`_CLIMB_cfconstr_pgmm`, x, prop, mu, sigma, rho, combos, k, df, lambda, citermax, tol, LASSO, bound)
}

cduvnorm <- function(x, mu, sigma) {
    .Call(`_CLIMB_cduvnorm`, x, mu, sigma)
}

cmarg_ll_gmm <- function(z, mu, sigma, prop, combos, k) {
    .Call(`_CLIMB_cmarg_ll_gmm`, z, mu, sigma, prop, combos, k)
}

cll_gmm <- function(z, mu, sigma, rho, prop, combos, k) {
    .Call(`_CLIMB_cll_gmm`, z, mu, sigma, rho, prop, combos, k)
}

